(()=>{
  const SYNC_MS=15000; let syncing=false,lastSnapshot='';
  const e=v=>typeof esc==='function'?esc(v):String(v??'');
  const val=(v,fallback='—')=>v===undefined||v===null||v===''?fallback:String(v);
  const labelDate=v=>{try{return typeof dateBR==='function'?dateBR(v):val(v)}catch{return val(v)}};
  const norm=v=>String(v??'').trim().toLowerCase();
  function freqRows(x){const f=x&&x.frequencia&&typeof x.frequencia==='object'?x.frequencia:{};const rows=Object.entries(f).sort((a,b)=>String(b[0]).localeCompare(String(a[0]))).slice(0,12);return rows.length?rows.map(([d,s])=>`<div class="convertHistory"><span>${e(labelDate(d))}</span><b>${e(s)}</b></div>`).join(''):'<p class="mut">Nenhuma frequência dominical registrada.</p>'}
  function templeRows(x){const t=x&&x.visitaTemplo&&typeof x.visitaTemplo==='object'?x.visitaTemplo:{};const rows=Object.entries(t).sort((a,b)=>String(b[0]).localeCompare(String(a[0]))).slice(0,12);return rows.length?rows.map(([d,s])=>`<div class="convertHistory"><span>${e(labelDate(d.length===7?d+'-01':d))}</span><b>${e(s)}</b></div>`).join(''):'<p class="mut">Nenhuma ida ao templo registrada.</p>'}
  function stateOf(v,type){const n=norm(v);if(!n)return'neutral';if(type==='interview')return n.includes('nunca')||n.includes('não registrada')?'warn':'ok';if(n==='sim'||n==='possui'||n.includes('recebeu')||n.includes('realiz')||n.includes('ativo'))return'ok';if(n.includes('não se aplica'))return'neutral';if(n==='não'||n.includes('nao')||n.includes('não possui')||n.includes('nunca'))return'warn';if(n.includes('parcial')||n.includes('processo')||n.includes('andamento'))return'mid';return'neutral'}
  function indicator(label,value,type=''){const v=val(value);return `<div class="convertIndicator ${stateOf(v,type)}"><span>${e(label)}</span><b>${e(v)}</b></div>`}
  function row(label,value){return `<div class="convertDetail"><span>${e(label)}</span><b>${e(val(value))}</b></div>`}
  function profile(x,i){const interview=x.nuncaEntrevistado?'Nunca entrevistado':x.ultimaEntrevista?labelDate(x.ultimaEntrevista):'Não registrada';const ministers=x.ministradores==='Possui'&&x.ministradoresNomes?`${x.ministradores} · ${x.ministradoresNomes}`:val(x.ministradores);const calling=x.chamado==='Possui'&&x.chamadoQual?`${x.chamado} · ${x.chamadoQual}`:val(x.chamado);return `<div class="convertCard"><button class="convertToggle" data-convert="${i}"><span><b>${e(x.nome)}</b><small>${e(val(x.statusMembro,'Ativo'))} · Quórum de Élderes</small></span><strong>⌄</strong></button><div class="convertProfile" id="convert-${i}" hidden><div class="convertIndicators">${indicator('Entrevista',interview,'interview')}${indicator('Sacerdócio',x.sacerdocio)}${indicator('Recomendação',x.recomendacao)}${indicator('Ministradores',x.ministradores)}${indicator('Chamado',x.chamado)}${indicator('Bênção patriarcal',x.bencaoPatriarcal)}</div><div class="convertInfo">${row('Ministradores / amigos',ministers)}${row('Chamado',calling)}</div><div class="convertSub"><h3>Frequência dominical</h3>${freqRows(x)}</div><div class="convertSub"><h3>Templo</h3>${templeRows(x)}</div></div></div>`}
  window.convertsView=function(){const a=Array.isArray(converts)?converts:[];return `<div class="hero convertHero"><div class="eyebrow light">Acompanhamento</div><h2>Recém-conversos</h2><div class="mut">${a.length} ${a.length===1?'pessoa acompanhada':'pessoas acompanhadas'} · dados sincronizados automaticamente</div></div>${section('Progresso no caminho do discípulo',a.length?a.map(profile).join(''):'<p class="mut">Nenhum recém-converso do Quórum de Élderes encontrado.</p>','Toque em uma pessoa para visualizar os indicadores e o histórico. A edição continua sendo feita no app de origem.')}`};
  document.addEventListener('click',ev=>{const b=ev.target.closest('[data-convert]');if(!b)return;const p=document.getElementById('convert-'+b.dataset.convert);if(p)p.hidden=!p.hidden});
  async function refreshConverts(){if(syncing||!token||!me)return;syncing=true;try{const j=await call('get');const fresh=Array.isArray(j.converts)?j.converts:[];const snap=JSON.stringify(fresh);if(snap!==lastSnapshot){converts=fresh;lastSnapshot=snap;if(currentTab==='Recém-conversos')renderTab()}}catch(err){console.warn('Sincronização de recém-conversos adiada:',err?.message||err)}finally{syncing=false}}
  lastSnapshot=JSON.stringify(Array.isArray(converts)?converts:[]);setInterval(refreshConverts,SYNC_MS);window.addEventListener('focus',refreshConverts,{passive:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshConverts()});
  const style=document.createElement('style');style.textContent=`.convertHero{margin-bottom:18px}.convertCard{border-bottom:1px solid #edf2f1}.convertCard:last-child{border-bottom:0}.convertToggle{width:100%;border:0;background:#fff;padding:16px 14px;display:flex;justify-content:space-between;align-items:center;text-align:left;color:var(--ink)}.convertToggle b,.convertToggle small{display:block}.convertToggle b{font-size:14px}.convertToggle small{margin-top:4px;font-size:10.5px}.convertToggle strong{color:var(--teal);font-size:16px}.convertProfile{padding:0 14px 17px}.convertIndicators{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;background:var(--line);border:1px solid var(--line);border-radius:11px;overflow:hidden;margin:2px 0 14px}.convertIndicator{background:#fff;padding:11px 10px;min-height:68px;border-left:3px solid #aab6b5}.convertIndicator span,.convertIndicator b{display:block}.convertIndicator span{font-size:9.5px;color:var(--mut);margin-bottom:5px}.convertIndicator b{font-size:11px;line-height:1.25}.convertIndicator.ok{border-left-color:#3d8a72}.convertIndicator.mid{border-left-color:#b78a36}.convertIndicator.warn{border-left-color:#b65b50}.convertInfo{border-top:1px solid var(--line)}.convertDetail{display:grid;grid-template-columns:minmax(130px,.8fr) 1.2fr;gap:14px;padding:10px 0;border-bottom:1px solid #edf0ef}.convertDetail span{font-size:10.5px;color:var(--mut)}.convertDetail b{font-size:11.5px;text-align:right}.convertSub{margin-top:16px;padding-top:4px;border-top:1px solid var(--line)}.convertSub h3{font-size:12px;color:var(--teal);margin:10px 0 5px}.convertHistory{display:flex;justify-content:space-between;gap:12px;padding:8px 0;border-top:1px solid #edf0ef;font-size:10.5px}.convertHistory span{color:var(--mut)}@media(max-width:650px){.convertIndicators{grid-template-columns:repeat(2,minmax(0,1fr))}.convertToggle{padding:15px 12px}.convertProfile{padding-left:12px;padding-right:12px}}@media(max-width:380px){.convertIndicators{grid-template-columns:1fr}.convertDetail{grid-template-columns:1fr}.convertDetail b{text-align:left;margin-top:-7px}}`;document.head.appendChild(style);
})();