(()=>{'use strict';
const D=x=>window.dateBR?dateBR(x):String(x||''),E=x=>window.esc?esc(x):String(x??''),C=x=>String(x??'').trim();let items=[],polling=false,saveTimers={};
const statusLabel=s=>s==='completed'?'Concluída':s==='progress'?'Em andamento':'Pendente';
async function refreshItems(render=true){if(!token||polling)return;polling=true;try{const r=await call('meetingItems');items=r.items||[];window.qvMeetingItems=items;if(render)refreshVisible()}catch(e){console.warn('sync items',e)}finally{polling=false}}
function byCycle(cycle,type){return items.filter(x=>x.meeting_cycle===cycle&&(!type||x.item_type===type))}
function actionCompact(x){return `<div class="collabCompact"><b>${E(x.title||'Ação')}</b><small>${E(x.assignee||'Sem responsável')}${x.due_date?' · até '+D(x.due_date):''}</small></div>`}
function visitCompact(x){return `<div class="collabCompact"><b>${E(x.title||'Irmão/família')}</b><small>${x.visit_date?D(x.visit_date):'Data a definir'}${x.visit_time?' · '+E(x.visit_time):''}${x.assignee?' · '+E(x.assignee):''}</small></div>`}
function previousMeetingDate(cycle){const a=(state.meetings||[]).filter(m=>(m.sourceDate||m.date)<cycle).sort((a,b)=>String(b.sourceDate||b.date).localeCompare(String(a.sourceDate||a.date)));return a[0]?.date||a[0]?.sourceDate||''}
function kudos(cycle){const prev=previousMeetingDate(cycle);if(!prev)return[];const cur=(state.meetings||[]).find(m=>(m.sourceDate||m.date)===cycle)?.date||new Date().toISOString().slice(0,10);return items.filter(x=>x.item_type==='action'&&x.status==='completed'&&x.completed_at&&String(x.completed_at).slice(0,10)>prev&&String(x.completed_at).slice(0,10)<=cur)}
function options(){return '<option value="">Selecione</option>'+((typeof PRESIDENCY!=='undefined'?PRESIDENCY:[])||[]).map(n=>`<option>${E(n)}</option>`).join('')}
function collabBlock(cycle){const a=byCycle(cycle,'action'),v=byCycle(cycle,'visit'),k=kudos(cycle);return `<div class="collabMeeting" data-cycle="${cycle}">${k.length?`<div class="kudos"><h4>Concluídas desde a última reunião</h4><small>Momento de reconhecer e agradecer.</small>${k.map(x=>`<div>✓ <b>${E(x.title)}</b> · ${E(x.assignee||'')}</div>`).join('')}</div>`:''}<div class="collabHead"><h4>Ações da ata</h4><button class="mini" data-collab-open="action" data-cycle="${cycle}">+ Ação</button></div><div data-collab-list="action">${a.length?a.map(actionCompact).join(''):'<p class="mut">Nenhuma ação nesta ata.</p>'}</div><div class="collabForm" data-collab-form="action" hidden><label>Ação<textarea rows="2" data-cf="title"></textarea></label><label>Responsável<select data-cf="assignee">${options()}</select></label><label>Prazo<input type="date" data-cf="due"></label><button class="primary" data-collab-add="action" data-cycle="${cycle}">Adicionar ação</button></div><div class="collabHead"><h4>Visitas programadas</h4><button class="mini" data-collab-open="visit" data-cycle="${cycle}">+ Visita</button></div><div data-collab-list="visit">${v.length?v.map(visitCompact).join(''):'<p class="mut">Nenhuma visita nesta ata.</p>'}</div><div class="collabForm" data-collab-form="visit" hidden><label>Irmão / família<input data-cf="title"></label><label>Responsável<select data-cf="assignee">${options()}</select></label><label>Data<input type="date" data-cf="date"></label><label>Horário<input type="time" data-cf="time"></label><button class="primary" data-collab-add="visit" data-cycle="${cycle}">Adicionar visita</button></div><button class="mini meetingShareBtn" data-meeting-share="${cycle}">Compartilhar ata</button><small class="autoSaveHint">Alterações da ata são salvas automaticamente.</small></div>`}
function enhanceMeetings(){if(currentTab!=='Presidência')return;document.querySelectorAll('.scheduleRow > .inlinePlan[id^="m-"]').forEach(panel=>{const cycle=panel.id.slice(2);if(panel.querySelector('.collabMeeting'))return;const oldToggle=[...panel.querySelectorAll('.scheduleToggle.sub')].find(x=>/Nova ação/i.test(x.textContent));if(oldToggle){oldToggle.style.display='none';const target=document.getElementById(oldToggle.dataset.target);if(target)target.style.display='none'}const mt=panel.querySelector('.minuteTasks');if(mt)mt.style.display='none';const save=[...panel.querySelectorAll('button')].find(b=>/Salvar ata/i.test(b.textContent));if(save){save.textContent='Salvar agora';save.insertAdjacentHTML('beforebegin',collabBlock(cycle))}else panel.insertAdjacentHTML('beforeend',collabBlock(cycle))})}
function taskCard(x){return `<div class="collabTask"><div><b>${E(x.title)}</b><small>${E(x.assignee||'Sem responsável')}${x.due_date?' · Prazo '+D(x.due_date):''} · Ata ${D(x.meeting_cycle)}</small></div><select data-item-status="${x.id}"><option value="pending" ${x.status==='pending'?'selected':''}>Pendente</option><option value="progress" ${x.status==='progress'?'selected':''}>Em andamento</option><option value="completed" ${x.status==='completed'?'selected':''}>Concluída</option></select></div>`}
function dashboard(){if(currentTab!=='Início')return;const root=document.getElementById('view');if(!root)return;root.querySelectorAll('.section').forEach(s=>{if(/Minhas tarefas/i.test(s.querySelector('h2')?.textContent||''))s.classList.add('legacyTasks')});let box=root.querySelector('.collabDashboard');if(!box){box=document.createElement('div');box.className='section collabDashboard';root.appendChild(box)}const pending=items.filter(x=>x.item_type==='action'&&x.status==='pending'),progress=items.filter(x=>x.item_type==='action'&&x.status==='progress'),recent=items.filter(x=>x.item_type==='action'&&x.status==='completed').sort((a,b)=>String(b.completed_at).localeCompare(String(a.completed_at))).slice(0,8);box.innerHTML=`<div class="sectionHead"><h2>Ações da Presidência</h2><div class="mut">Painel compartilhado pela presidência e secretários.</div></div><div class="sectionBody"><div class="taskGroup"><h3>Pendentes <span>${pending.length}</span></h3>${pending.length?pending.map(taskCard).join(''):'<p class="mut">Nenhuma.</p>'}</div><div class="taskGroup"><h3>Em andamento <span>${progress.length}</span></h3>${progress.length?progress.map(taskCard).join(''):'<p class="mut">Nenhuma.</p>'}</div><div class="taskGroup recent"><h3>Concluídas recentemente <span>${recent.length}</span></h3>${recent.length?recent.map(taskCard).join(''):'<p class="mut">Nenhuma.</p>'}</div></div>`}
function refreshVisible(){if(currentTab==='Início')dashboard();if(currentTab==='Presidência'){document.querySelectorAll('.collabMeeting').forEach(old=>{const cycle=old.dataset.cycle,was=[...old.querySelectorAll('.collabForm')].find(x=>!x.hidden)?.dataset.collabForm;const n=document.createElement('div');n.innerHTML=collabBlock(cycle);const fresh=n.firstElementChild;if(was)fresh.querySelector(`[data-collab-form="${was}"]`).hidden=false;old.replaceWith(fresh)})}}
function captureMeeting(panel){const cycle=panel.id.slice(2),x=(state.meetings||[]).find(m=>(m.sourceDate||m.date)===cycle)||{};const v=id=>document.getElementById(id)?.value||'';const obj={sourceDate:cycle,date:v(panel.id+'-date'),thought:v(panel.id+'-thought').trim(),openingPrayer:v(panel.id+'-open').trim(),closingPrayer:v(panel.id+'-close').trim(),agenda:v(panel.id+'-agenda').trim(),participantList:(typeof PRESIDENCY!=='undefined'?PRESIDENCY:[]).filter((p,i)=>document.getElementById(panel.id+'-p'+i)?.checked)};if(Object.keys(x).length)Object.assign(x,obj);else state.meetings.push(obj);return cycle}
function autosave(panel){const cycle=captureMeeting(panel);clearTimeout(saveTimers[cycle]);saveTimers[cycle]=setTimeout(async()=>{try{await call('save',{payload:state});const h=panel.querySelector('.autoSaveHint');if(h)h.textContent='Salvo automaticamente ✓'}catch(e){const h=panel.querySelector('.autoSaveHint');if(h)h.textContent='Não foi possível salvar agora.'}},700)}
async function add(type,cycle,form,btn){const title=C(form.querySelector('[data-cf="title"]')?.value);if(!title)return alert(type==='action'?'Informe a ação.':'Informe o irmão ou família.');btn.disabled=true;try{const r=await call('addMeetingItem',{meetingCycle:cycle,itemType:type,title,assignee:form.querySelector('[data-cf="assignee"]')?.value||'',dueDate:type==='action'?(form.querySelector('[data-cf="due"]')?.value||null):null,visitDate:type==='visit'?(form.querySelector('[data-cf="date"]')?.value||null):null,visitTime:type==='visit'?(form.querySelector('[data-cf="time"]')?.value||null):null});items.push(r.item);form.querySelectorAll('input,textarea,select').forEach(x=>x.value='');form.hidden=true;refreshVisible()}catch(e){alert(e.message||'Não foi possível adicionar.')}finally{btn.disabled=false}}
function meetingText(cycle){const m=(state.meetings||[]).find(x=>(x.sourceDate||x.date)===cycle)||{},a=byCycle(cycle,'action'),v=byCycle(cycle,'visit'),lines=['*Ata — Reunião da Presidência do Quórum de Élderes*','Ala Vila Jacuí',`📅 ${D(m.date||cycle)}`];if(m.participantList?.length)lines.push('','*Participantes*',m.participantList.map(x=>'• '+x).join('\n'));if(C(m.thought))lines.push('','*Pensamento espiritual*',C(m.thought));if(C(m.agenda))lines.push('','*Assuntos tratados*',C(m.agenda));if(a.length)lines.push('','*Ações definidas*',a.map(x=>`• ${C(x.title)}${x.assignee?' — '+x.assignee:''}${x.due_date?' · até '+D(x.due_date):''}`).join('\n'));if(v.length)lines.push('','*Visitas programadas*',v.map(x=>`• ${C(x.title)}${x.visit_date?' — '+D(x.visit_date):''}${x.visit_time?' às '+x.visit_time:''}${x.assignee?' · '+x.assignee:''}`).join('\n'));return lines.join('\n')}
async function share(cycle,b){captureMeeting(document.getElementById('m-'+cycle));const text=meetingText(cycle);try{if(navigator.share)await navigator.share({title:'Ata da Presidência',text});else{await navigator.clipboard.writeText(text);b.textContent='Ata copiada ✓'}}catch(e){if(e?.name!=='AbortError')window.prompt('Copie a ata:',text)}}
document.addEventListener('click',e=>{const open=e.target.closest('[data-collab-open]');if(open){const root=open.closest('.collabMeeting'),f=root.querySelector(`[data-collab-form="${open.dataset.collabOpen}"]`);f.hidden=!f.hidden;return}const addb=e.target.closest('[data-collab-add]');if(addb){add(addb.dataset.collabAdd,addb.dataset.cycle,addb.closest('.collabForm'),addb);return}const sh=e.target.closest('[data-meeting-share]');if(sh){share(sh.dataset.meetingShare,sh);return}});
document.addEventListener('change',async e=>{const s=e.target.closest('[data-item-status]');if(s){const old=items.find(x=>x.id===s.dataset.itemStatus);try{const r=await call('updateMeetingItem',{id:s.dataset.itemStatus,status:s.value});Object.assign(old,r.item);refreshVisible()}catch(err){alert(err.message);refreshVisible()}return}const p=e.target.closest('.scheduleRow > .inlinePlan[id^="m-"]');if(p)autosave(p)});
document.addEventListener('input',e=>{const p=e.target.closest('.scheduleRow > .inlinePlan[id^="m-"]');if(p&&!e.target.closest('.collabForm'))autosave(p)});
const baseSave=window.saveMeeting;window.saveMeeting=saveMeeting=async function(cycle){const p=document.getElementById('m-'+cycle);if(!p)return baseSave?.(cycle);captureMeeting(p);await call('save',{payload:state});const h=p.querySelector('.autoSaveHint');if(h)h.textContent='Salvo ✓'};
const old=window.renderTab;window.renderTab=function(){const r=old.apply(this,arguments);setTimeout(()=>{enhanceMeetings();dashboard()},80);return r};
setInterval(()=>{if(token&&me)refreshItems(true)},4000);document.addEventListener('DOMContentLoaded',()=>setTimeout(async()=>{await refreshItems(false);enhanceMeetings();dashboard()},500));
const st=document.createElement('style');st.textContent=`.legacyTasks,.sv7Filters{display:none!important}.collabMeeting{margin-top:18px;padding-top:14px;border-top:1px solid var(--line)}.collabHead{display:flex;align-items:center;justify-content:space-between;margin-top:14px}.collabHead h4{margin:0}.collabCompact{padding:9px 0;border-bottom:1px solid var(--line)}.collabCompact b,.collabCompact small{display:block}.collabForm{margin:9px 0 15px;padding:13px;border-left:3px solid var(--teal);background:rgba(15,107,104,.05)}.meetingShareBtn{width:100%;margin-top:18px;min-height:44px}.autoSaveHint{display:block;text-align:center;margin-top:7px}.collabTask{display:grid;grid-template-columns:1fr 160px;gap:12px;align-items:center;padding:12px 0;border-top:1px solid var(--line)}.collabTask b,.collabTask small{display:block}.collabTask select{margin:0}.taskGroup h3{display:flex;justify-content:space-between;font-size:14px;margin:16px 0 5px}.taskGroup h3 span{color:var(--teal)}.kudos{border-left:3px solid #4b8b6f;padding:10px 12px;margin:5px 0 15px;background:rgba(75,139,111,.08)}.kudos h4{margin:0}.kudos>div{padding-top:7px;font-size:12px}@media(max-width:600px){.collabTask{grid-template-columns:1fr}.collabTask select{min-height:44px}.collabHead .mini{min-height:44px}}html[data-theme=dark] .collabForm,html[data-theme=dark] .kudos{background:#101d1b!important}html[data-theme=dark] .collabTask,html[data-theme=dark] .collabCompact{border-color:#30413e!important}`;document.head.appendChild(st)
})();