let currentTab='Início';
const DAY=86400000;
const PRESIDENCY=['Wellington Antônio da Silva','Kevin Alexander Maurera Martinez','Alan C Francisco Cardoso','Rony Bento','Fabricio Jose de Lima','Rodrigo Afonso de Morais'];
const $=id=>document.getElementById(id);
function ensure(){state=state&&typeof state==='object'?state:{};for(const k of ['members','lessons','meetings','tasks','interviews','assistance'])state[k]=Array.isArray(state[k])?state[k].filter(Boolean):[];state.attendance=state.attendance&&typeof state.attendance==='object'&&!Array.isArray(state.attendance)?state.attendance:{};}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function iso(d){return d.toISOString().slice(0,10)}
function dateBR(v){if(!v)return'Sem prazo';let m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return esc(v);let y=+m[1],mo=+m[2],da=+m[3];if(mo>12&&da<=12)[mo,da]=[da,mo];let d=new Date(y,mo-1,da,12);return Number.isNaN(d.getTime())?esc(v):new Intl.DateTimeFormat('pt-BR').format(d)}
function sundays(n=20){let d=new Date();d.setHours(12,0,0,0);while(d.getDay())d=new Date(d.getTime()+DAY);let a=[];for(let i=0;i<n;i++){let x=new Date(d.getTime()+i*7*DAY),o=Math.ceil(x.getDate()/7);if(o<=4)a.push({date:iso(x),label:`${o}º domingo · ${dateBR(iso(x))}`})}return a}
function meetingDates(n=12){let d=new Date();d.setHours(12,0,0,0);while(d.getDay())d=new Date(d.getTime()+DAY);return Array.from({length:n},(_,i)=>({date:iso(new Date(d.getTime()+i*14*DAY))}))}
function opts(sel='',list=PRESIDENCY){return'<option value="">Selecione</option>'+list.map(p=>`<option value="${esc(p)}" ${p===sel?'selected':''}>${esc(p)}</option>`).join('')}
function memberOpts(sel=''){return opts(sel,state.members.map(m=>m.name).filter(Boolean).sort((a,b)=>a.localeCompare(b,'pt-BR')))}
function section(title,body,sub=''){return`<div class="section"><div class="sectionHead"><h2>${title}</h2>${sub?`<div class="mut">${sub}</div>`:''}</div><div class="sectionBody">${body}</div></div>`}
function taskCard(t){let i=state.tasks.indexOf(t),hist=(t.history||[]).filter(h=>h.from&&h.to&&h.from!=='Ata').map(h=>`<small>Redesignada: ${esc(h.from)} → ${esc(h.to)} · ${dateBR(String(h.at||'').slice(0,10))}</small>`).join('');return`<div class="item"><b>${esc(t.title)}</b><small>${esc(t.assignee||'Sem responsável')} · Prazo ${dateBR(t.due)} · ${t.done?'Concluída':'Pendente'}</small>${hist}<div class="actionsRow">${!t.done?`<button class="mini" data-act="done" data-i="${i}">Concluir</button><button class="mini" data-act="reassign" data-i="${i}">Redesignar</button>`:''}<button class="mini danger" data-act="askDelete" data-i="${i}">Excluir</button></div><div id="reas-${i}" class="inlinePlan" hidden><label>Novo responsável<select id="rp-${i}">${opts(t.assignee)}</select></label><label>Novo prazo<input type="date" id="rd-${i}" value="${esc(t.due||'')}"></label><button class="primary" data-act="saveReassign" data-i="${i}">Salvar redesignação</button></div><div id="del-${i}" class="inlineConfirm" hidden><b>Excluir este registro?</b><span>Use apenas para teste ou lançamento feito por engano.</span><button class="mini danger" data-act="delete" data-i="${i}">Confirmar exclusão</button><button class="mini" data-act="cancelDelete" data-i="${i}">Cancelar</button></div></div>`}
function myTasks(){let a=state.tasks.filter(t=>!t.done&&t.assignee===me.name);return section('Minhas tarefas',a.length?a.map(taskCard).join(''):'<p class="mut">Nenhuma tarefa pendente.</p>','Designações atribuídas a você.')}
function home(){let active=state.members.filter(m=>m.active).length,pending=state.tasks.filter(t=>!t.done).length,mine=state.tasks.filter(t=>!t.done&&t.assignee===me.name).length,next=sundays(1)[0];return`<div class="hero"><div class="eyebrow light">${esc(me.name.split(' ')[0])}</div><h2>Visão da presidência</h2><div class="mut">Planejamento, cuidado e acompanhamento do quórum.</div></div><div class="metrics"><div><b>${active}</b><span>irmãos ativos</span></div><div><b>${pending}</b><span>ações pendentes</span></div><div><b>${mine}</b><span>para você</span></div><div><b>${next?dateBR(next.date):'—'}</b><span>próxima aula</span></div></div>${myTasks()}`}
function findMeeting(d){return state.meetings.find(x=>x.sourceDate===d||x.date===d)||{}}
function meetingRow(s){let x=findMeeting(s.date),id='m-'+s.date,ts=state.tasks.filter(t=>t.sourceDate===s.date);return`<div class="scheduleRow"><button class="scheduleToggle" data-act="toggle" data-target="${id}"><span><b>${dateBR(x.date||s.date)} · Reunião da Presidência</b><small>${esc(x.agenda||'Pauta não preparada')}</small></span><strong>⌄</strong></button><div id="${id}" class="inlinePlan" hidden><label>Data<input type="date" id="${id}-date" value="${esc(x.date||s.date)}"></label><label>Pensamento espiritual<input id="${id}-thought" value="${esc(x.thought||'')}"></label><label>Oração inicial<input id="${id}-open" value="${esc(x.openingPrayer||'')}"></label><label>Oração final<input id="${id}-close" value="${esc(x.closingPrayer||'')}"></label><div class="checkGroup"><b>Participantes</b>${PRESIDENCY.map((p,i)=>`<label><input type="checkbox" id="${id}-p${i}" ${(x.participantList||PRESIDENCY).includes(p)?'checked':''}> ${esc(p)}</label>`).join('')}</div><label>Pauta / assuntos<textarea id="${id}-agenda" rows="5">${esc(x.agenda||'')}</textarea></label><button class="scheduleToggle sub" data-act="toggle" data-target="task-${s.date}"><span><b>+ Nova ação a ser tomada</b><small>Registrar diretamente na ata</small></span><strong>⌄</strong></button><div id="task-${s.date}" class="inlinePlan nested" hidden><label>Ação<textarea id="tt-${s.date}" rows="3"></textarea></label><label>Responsável<select id="tp-${s.date}">${opts()}</select></label><label>Prazo<input type="date" id="td-${s.date}"></label><button class="primary" data-act="addTask" data-date="${s.date}">Adicionar à ata</button></div><div class="minuteTasks"><h4>Ações registradas nesta ata</h4>${ts.length?ts.map(taskCard).join(''):'<p class="mut">Nenhuma ação registrada.</p>'}</div><label>Revisar na próxima reunião<textarea id="${id}-review" rows="3">${esc(x.review||'')}</textarea></label><button class="primary" data-act="saveMeeting" data-date="${s.date}">Salvar ata</button></div></div>`}
function presidency(){return section('Programação da Presidência',meetingDates().map(meetingRow).join(''),'Reuniões quinzenais. Abra uma data para preparar a pauta e registrar a ata.')+myTasks()}
function lessonRow(s){let x=state.lessons.find(z=>z.date===s.date)||{},id='l-'+s.date,r=state.attendance[s.date]||{};return`<div class="scheduleRow"><button class="scheduleToggle" data-act="toggle" data-target="${id}"><span><b>${s.label}</b><small>${esc(x.topic||'Não planejada')}</small></span><strong>⌄</strong></button><div id="${id}" class="inlinePlan" hidden><label>Tema ou discurso<input id="${id}-topic" value="${esc(x.topic||'')}"></label><label>Professor<input id="${id}-teacher" value="${esc(x.teacher||'')}"></label><label>Oração inicial<input id="${id}-open" value="${esc(x.openingPrayer||'')}"></label><label>Oração final<input id="${id}-close" value="${esc(x.closingPrayer||'')}"></label><label>Número de visitantes<input type="number" min="0" id="${id}-vis" value="${+x.visitors||0}"></label><button class="primary" data-act="saveLesson" data-date="${s.date}">Salvar planejamento</button><div class="attendanceBox"><h3>Frequência</h3><p class="mut">Quem está na aula conta automaticamente na sacramental. Use “Só sacramental” para a exceção.</p>${state.members.filter(m=>m?.active).map(m=>{let real=state.members.indexOf(m),v=r[m.name]||{},mode=v.class?'class':v.sacrament?'sac':'abs';return`<div class="attendanceLine"><span>${esc(m.name)}</span><select id="att-${s.date}-${real}"><option value="abs" ${mode==='abs'?'selected':''}>Ausente</option><option value="class" ${mode==='class'?'selected':''}>Aula + Sacramental</option><option value="sac" ${mode==='sac'?'selected':''}>Só sacramental</option></select></div>`}).join('')||'<p class="mut">Cadastre ou ative irmãos na Base do Quórum para registrar frequência.</p>'}<button class="primary" data-act="saveAttendance" data-date="${s.date}">Salvar frequência</button></div></div></div>`}
function lessons(){return section('Programação de aulas',sundays().map(lessonRow).join(''),'1º, 2º, 3º e 4º domingos já disponíveis para planejamento.')}
function pct(d,k){let a=state.members.filter(m=>m?.active),r=state.attendance[d]||{};return a.length?Math.round(a.filter(m=>r[m.name]?.[k]).length/a.length*100):0}
function frequency(){let ds=Object.keys(state.attendance).sort().reverse(),rows=ds.map(d=>{let l=state.lessons.find(x=>x.date===d)||{};return`<div class="item"><b>${dateBR(d)}</b><small>Aula ${pct(d,'class')}% · Sacramental ${pct(d,'sacrament')}% · Visitantes ${+l.visitors||0}</small></div>`}).join('');return section('Painel de frequência',rows||'<p class="mut">Sem frequência registrada.</p>','Percentuais calculados somente sobre irmãos marcados como ativos.')}
function brothers(){let active=state.members.filter(m=>m.active),inactive=state.members.filter(m=>!m.active);let rows=list=>list.sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')).map(m=>{let i=state.members.indexOf(m);return`<div class="item brother"><div><b>${esc(m.name)}</b><small>${m.active?'Ativo':'Inativo'}</small></div><button class="mini" data-act="toggleMember" data-i="${i}">${m.active?'Marcar inativo':'Marcar ativo'}</button></div>`}).join('');return section('Base do Quórum',`<div class="splitTitle"><b>Ativos</b><span>${active.length}</span></div>${rows(active)||'<p class="mut">Nenhum irmão ativo.</p>'}<div class="splitTitle"><b>Inativos</b><span>${inactive.length}</span></div>${rows(inactive)||'<p class="mut">Nenhum irmão inativo.</p>'}`,'A situação ativo/inativo define quem entra no cálculo de frequência.')}
function ministering(){let rows=state.interviews.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map((x,i)=>`<div class="item"><b>${esc(x.member)}</b><small>${dateBR(x.date)} · Entrevistador: ${esc(x.interviewer)}</small>${x.notes?`<small>${esc(x.notes)}</small>`:''}<button class="mini danger" data-act="deleteInterview" data-i="${i}">Excluir</button></div>`).join('');return section('Entrevistas de ministração',`<button class="scheduleToggle sub" data-act="toggle" data-target="new-interview"><span><b>+ Registrar entrevista</b><small>Registro interno de acompanhamento</small></span><strong>⌄</strong></button><div id="new-interview" class="inlinePlan" hidden><label>Irmão entrevistado<select id="iv-member">${memberOpts()}</select></label><label>Entrevistador<select id="iv-interviewer">${opts(me.name)}</select></label><label>Data<input type="date" id="iv-date" value="${iso(new Date())}"></label><label>Observação<textarea id="iv-notes" rows="3"></textarea></label><button class="primary" data-act="saveInterview">Salvar entrevista</button></div>${rows||'<p class="mut">Nenhuma entrevista registrada neste app.</p>'}`,'Este registro apoia o acompanhamento da presidência; não substitui os registros oficiais da Igreja.')+myTasks()}
function convertsView(){let a=Array.isArray(converts)?converts:[];return section('Recém-conversos',a.length?a.map(x=>`<div class="item"><b>${esc(x.nome)}</b><small>${esc(x.statusMembro||'')}</small></div>`).join(''):'<p class="mut">Nenhum recém-converso do Quórum de Élderes encontrado.</p>','Dados recebidos automaticamente do acompanhamento de recém-conversos.')}
function assistance(){if(!me.assistance)return section('Ajudas','<p class="mut">Área restrita.</p>');let rows=state.assistance.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(x=>{let i=state.assistance.indexOf(x);return`<div class="item"><b>${esc(x.person)}</b><small>${dateBR(x.date)} · ${x.amount?Number(x.amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'Sem valor informado'}</small><small>${esc(x.description||'')}</small>${x.receiptName?`<small>Comprovante: ${esc(x.receiptName)}</small>`:''}<button class="mini danger" data-act="deleteAssistance" data-i="${i}">Excluir</button></div>`}).join('');return section('Ajudas',`<button class="scheduleToggle sub" data-act="toggle" data-target="new-help"><span><b>+ Registrar acompanhamento</b><small>Área exclusiva do presidente</small></span><strong>⌄</strong></button><div id="new-help" class="inlinePlan" hidden><label>Pessoa<input id="help-person"></label><label>Data<input type="date" id="help-date" value="${iso(new Date())}"></label><label>Valor (R$)<input id="help-amount" type="number" min="0" step="0.01"></label><label>Descrição<textarea id="help-description" rows="3"></textarea></label><label>Comprovante / referência<input id="help-receipt" placeholder="Nome ou referência do comprovante"></label><button class="primary" data-act="saveAssistance">Salvar registro</button></div>${rows||'<p class="mut">Nenhum registro.</p>'}`,'Registro de acompanhamento. A aprovação e administração de assistência continuam sob a autoridade do bispo.')}
async function accesses(){let v=$('view');v.innerHTML=section('Acessos','<p class="mut">Carregando perfis…</p>');try{let j=await call('profiles'),ps=j.profiles||j||[];let rows=Array.isArray(ps)?ps.map(p=>`<div class="item"><b>${esc(p.display_name||p.name)}</b><small>${esc(p.role_label||p.label||p.role)}</small><small>${p.password_ready?'Senha configurada':'Senha ainda não configurada'}</small></div>`).join(''):'';v.innerHTML=section('Acessos',rows||'<p class="mut">Nenhum perfil retornado.</p>','Perfis individuais da presidência. A alteração de senhas será habilitada quando o backend seguro estiver pronto.')}catch(e){v.innerHTML=section('Acessos',`<p class="mut">Não foi possível carregar os perfis: ${esc(e.message)}</p>`)} }
function renderTab(){ensure();document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('on',b.textContent.trim()===currentTab));let v=$('view');try{if(currentTab==='Início')v.innerHTML=home();else if(currentTab==='Presidência')v.innerHTML=presidency();else if(currentTab==='Aulas')v.innerHTML=lessons();else if(currentTab==='Frequência')v.innerHTML=frequency();else if(currentTab==='Irmãos')v.innerHTML=brothers();else if(currentTab==='Ministração')v.innerHTML=ministering();else if(currentTab==='Recém-conversos')v.innerHTML=convertsView();else if(currentTab==='Ajudas')v.innerHTML=assistance();else if(currentTab==='Acessos')accesses()}catch(e){console.error(e);v.innerHTML=section('Erro',`<p class="mut">${esc(e.message)}</p>`)}}
document.addEventListener('click',async e=>{let n=e.target.closest('#nav button');if(n){currentTab=n.textContent.trim();renderTab();return}let b=e.target.closest('[data-act]');if(!b)return;let a=b.dataset.act,i=+b.dataset.i;if(a==='toggle'){let el=$(b.dataset.target);if(el)el.hidden=!el.hidden;return}if(a==='done'){state.tasks[i].done=true;await saveState();renderTab()}else if(a==='reassign')$('reas-'+i).hidden=false;else if(a==='saveReassign'){let t=state.tasks[i],p=$('rp-'+i).value,d=$('rd-'+i).value;if(p){t.history=Array.isArray(t.history)?t.history:[];t.history.push({at:new Date().toISOString(),from:t.assignee,to:p});t.assignee=p;t.due=d;await saveState();renderTab()}}else if(a==='askDelete')$('del-'+i).hidden=false;else if(a==='cancelDelete')$('del-'+i).hidden=true;else if(a==='delete'){state.tasks.splice(i,1);await saveState();renderTab()}else if(a==='addTask')await addTask(b.dataset.date);else if(a==='saveMeeting')await saveMeeting(b.dataset.date);else if(a==='saveLesson')await saveLesson(b.dataset.date);else if(a==='saveAttendance')await saveAttendance(b.dataset.date);else if(a==='toggleMember'){state.members[i].active=!state.members[i].active;await saveState();renderTab()}else if(a==='saveInterview')await saveInterview();else if(a==='deleteInterview'){state.interviews.splice(i,1);await saveState();renderTab()}else if(a==='saveAssistance')await saveAssistance();else if(a==='deleteAssistance'){state.assistance.splice(i,1);await saveState();renderTab()}});
async function addTask(d){let title=$('tt-'+d).value.trim(),p=$('tp-'+d).value,due=$('td-'+d).value;if(!title||!p)return;state.tasks.push({title,assignee:p,due,sourceDate:d,type:'Ação da presidência',done:false,history:[{at:new Date().toISOString(),from:'Ata',to:p}]});await saveState();renderTab()}
async function saveMeeting(d){let id='m-'+d,x=findMeeting(d),obj={sourceDate:d,date:$(id+'-date').value,thought:$(id+'-thought').value.trim(),openingPrayer:$(id+'-open').value.trim(),closingPrayer:$(id+'-close').value.trim(),participantList:PRESIDENCY.filter((p,i)=>$(id+'-p'+i).checked),agenda:$(id+'-agenda').value.trim(),review:$(id+'-review').value.trim()};Object.keys(x).length?Object.assign(x,obj):state.meetings.push(obj);await saveState();renderTab()}
async function saveLesson(d){let id='l-'+d,x=state.lessons.find(z=>z.date===d),obj={date:d,topic:$(id+'-topic').value.trim(),teacher:$(id+'-teacher').value.trim(),openingPrayer:$(id+'-open').value.trim(),closingPrayer:$(id+'-close').value.trim(),visitors:+$(id+'-vis').value||0};x?Object.assign(x,obj):state.lessons.push(obj);await saveState();renderTab()}
async function saveAttendance(d){let r={};state.members.forEach((m,i)=>{if(!m?.active)return;let mode=$(`att-${d}-${i}`)?.value||'abs';r[m.name]={class:mode==='class',sacrament:mode!=='abs'}});state.attendance[d]=r;await saveState();renderTab()}
async function saveInterview(){let member=$('iv-member').value,interviewer=$('iv-interviewer').value,date=$('iv-date').value,notes=$('iv-notes').value.trim();if(!member||!interviewer||!date)return;state.interviews.push({member,interviewer,date,notes,createdAt:new Date().toISOString()});await saveState();renderTab()}
async function saveAssistance(){let person=$('help-person').value.trim(),date=$('help-date').value,amount=+$('help-amount').value||0,description=$('help-description').value.trim(),receiptName=$('help-receipt').value.trim();if(!person||!date)return;state.assistance.push({person,date,amount,description,receiptName,createdAt:new Date().toISOString()});await saveState();renderTab()}
async function saveState(){try{await call('save',{payload:state})}catch(e){console.error(e);let v=$('view');v.insertAdjacentHTML('afterbegin',`<div class="saveError">Não foi possível salvar: ${esc(e.message)}</div>`);throw e}}
